In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
X, y = load_iris(return_X_y=True)

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[-0.31786434, -0.33305175, -0.14214484,  0.07930516],
       [-0.31786434, -0.0979564 ,  0.37301095,  0.34365569],
       [-1.0421122 ,  1.31261571, -1.40141454, -1.37462275],
       [-0.92140422,  1.07752036, -1.40141454, -1.37462275],
       [-0.55928029,  0.84242501, -1.22969595, -1.37462275],
       [ 1.0099234 , -0.0979564 ,  0.77368768,  1.4010578 ],
       [-0.31786434, -0.5681471 ,  0.60196908,  1.00453201],
       [ 0.5270915 , -1.74362386,  0.31577142,  0.07930516],
       [-0.43857231, -1.74362386,  0.08681329,  0.07930516],
       [-0.80069624, -0.80324245,  0.02957376,  0.21148042],
       [ 0.16496757,  0.84242501,  0.37301095,  0.47583095],
       [-1.16282017, -0.0979564 , -1.40141454, -1.37462275],
       [-0.31786434, -1.27343315,  0.02957376, -0.18504537],
       [-0.92140422, -1.27343315, -0.48558203, -0.18504537],
       [-0.07644839, -0.80324245,  0.14405282, -0.31722063],
       [ 0.04425959, -0.0979564 ,  0.20129235,  0.34365569],
       [-0.80069624,  2.48809247, -1.34417501, -1.50679801],
       [ 1.0099234 , -0.0979564 ,  0.65920861,  0.60800622],
       [ 1.73417126, -0.33305175,  1.40332253,  0.74018148],
       [-0.43857231,  1.07752036, -1.45865408, -1.37462275],
       [ 2.21700317, -0.5681471 ,  1.63228066,  1.00453201],
       [-0.19715636, -0.0979564 ,  0.20129235, -0.05287011],
       [ 2.21700317, -0.0979564 ,  1.28884346,  1.4010578 ],
       [-0.55928029, -0.0979564 ,  0.37301095,  0.34365569],
       [ 1.0099234 ,  0.13713895,  1.0026458 ,  1.53323307],
       [ 1.0099234 ,  0.60732966,  1.05988534,  1.66540833],
       [ 1.85487924, -0.5681471 ,  1.28884346,  0.87235674],
       [-1.16282017,  0.13713895, -1.34417501, -1.50679801],
       [-0.07644839, -0.5681471 ,  0.71644814,  1.53323307],
       [-0.43857231, -1.0383378 ,  0.31577142, -0.05287011],
       [-0.19715636, -1.27343315,  0.65920861,  1.00453201],
       [-1.28352815, -0.0979564 , -1.40141454, -1.24244748],
       [ 0.28567554, -0.5681471 ,  0.08681329,  0.07930516],
       [ 1.0099234 , -1.27343315,  1.11712487,  0.74018148],
       [ 0.64779947, -0.80324245,  0.83092721,  0.87235674],
       [-0.92140422,  0.60732966, -1.22969595, -0.97809696],
       [ 2.09629519, -0.0979564 ,  1.57504113,  1.13670727],
       [-0.55928029,  0.84242501, -1.34417501, -1.11027222],
       [-0.07644839, -0.80324245,  0.71644814,  0.87235674],
       [ 1.25133936,  0.13713895,  0.88816674,  1.13670727],
       [ 0.16496757, -1.97871921,  0.65920861,  0.34365569],
       [ 0.64779947,  0.13713895,  0.94540627,  0.74018148],
       [-1.16282017, -1.27343315,  0.37301095,  0.60800622],
       [-0.19715636, -1.0383378 , -0.19938437, -0.31722063],
       [-1.88706803, -0.0979564 , -1.57313314, -1.50679801],
       [ 0.5270915 , -0.33305175,  1.0026458 ,  0.74018148],
       [-1.5249441 ,  0.84242501, -1.40141454, -1.24244748],
       [ 0.76850745, -0.0979564 ,  0.77368768,  1.00453201],
       [-0.80069624,  0.84242501, -1.40141454, -1.37462275],
       [-0.92140422,  1.78280641, -1.34417501, -1.24244748],
       [ 0.76850745, -0.0979564 ,  0.94540627,  0.74018148],
       [-1.28352815,  0.84242501, -1.11521688, -1.37462275],
       [ 1.25133936,  0.37223431,  1.05988534,  1.4010578 ],
       [ 2.21700317,  1.78280641,  1.63228066,  1.26888254],
       [-0.92140422,  1.07752036, -1.40141454, -1.24244748],
       [-1.16282017,  1.31261571, -1.40141454, -1.50679801],
       [-0.67998827,  1.54771106, -1.34417501, -1.37462275],
       [ 0.5270915 , -0.5681471 ,  0.71644814,  0.34365569],
       [-0.07644839, -0.80324245,  0.71644814,  0.87235674],
       [ 0.40638352, -1.97871921,  0.37301095,  0.34365569],
       [-1.0421122 , -2.44890991, -0.19938437, -0.31722063],
       [ 0.04425959, -0.0979564 ,  0.71644814,  0.74018148],
       [-0.07644839, -0.80324245,  0.02957376, -0.05287011],
       [-0.19715636, -0.5681471 ,  0.37301095,  0.07930516],
       [-1.0421122 , -1.74362386, -0.31386343, -0.31722063],
       [-0.80069624,  1.07752036, -1.34417501, -1.37462275],
       [-1.0421122 ,  1.07752036, -1.45865408, -1.24244748],
       [ 0.5270915 , -1.27343315,  0.65920861,  0.87235674],
       [ 2.45841912,  1.78280641,  1.46056206,  1.00453201],
       [-0.19715636, -0.33305175,  0.20129235,  0.07930516],
       [-1.76636006,  0.37223431, -1.45865408, -1.37462275],
       [-1.76636006, -0.0979564 , -1.45865408, -1.37462275],
       [-0.19715636,  3.19337852, -1.34417501, -1.11027222],
       [-1.0421122 ,  1.07752036, -1.28693548, -0.84592169],
       [ 0.64779947, -0.5681471 ,  1.0026458 ,  1.26888254],
       [ 0.5270915 ,  0.60732966,  1.23160393,  1.66540833],
       [ 1.25133936,  0.13713895,  0.71644814,  1.4010578 ],
       [-0.92140422,  1.78280641, -1.11521688, -1.11027222],
       [-0.31786434, -0.80324245,  0.20129235,  0.07930516],
       [ 0.40638352, -0.33305175,  0.25853189,  0.07930516],
       [ 1.61346329,  1.31261571,  1.28884346,  1.66540833],
       [ 0.5270915 , -0.80324245,  0.60196908,  0.74018148],
       [-0.19715636, -0.5681471 ,  0.14405282,  0.07930516],
       [-0.43857231,  2.72318782, -1.40141454, -1.37462275],
       [ 1.13063138, -0.5681471 ,  0.54472955,  0.21148042],
       [-1.28352815,  0.84242501, -1.28693548, -1.37462275],
       [ 0.76850745,  0.37223431,  0.71644814,  1.00453201],
       [ 0.28567554, -0.0979564 ,  0.60196908,  0.74018148],
       [-1.40423613,  0.37223431, -1.28693548, -1.37462275],
       [ 0.28567554, -0.0979564 ,  0.43025048,  0.21148042],
       [-0.92140422,  0.84242501, -1.34417501, -1.37462275],
       [-0.43857231, -1.27343315,  0.08681329,  0.07930516],
       [ 0.40638352,  0.84242501,  0.88816674,  1.4010578 ],
       [ 0.76850745, -0.0979564 ,  1.11712487,  1.26888254],
       [ 0.76850745, -0.5681471 ,  0.43025048,  0.34365569],
       [-1.0421122 ,  0.37223431, -1.51589361, -1.37462275],
       [-1.16282017,  0.13713895, -1.34417501, -1.37462275],
       [-1.5249441 ,  1.31261571, -1.63037267, -1.37462275],
       [-0.92140422,  1.54771106, -1.34417501, -1.11027222],
       [ 0.64779947, -0.33305175,  0.25853189,  0.07930516],
       [-0.07644839, -1.0383378 ,  0.08681329, -0.05287011],
       [ 1.0099234 ,  0.13713895,  0.31577142,  0.21148042],
       [ 0.16496757, -0.33305175,  0.37301095,  0.34365569],
       [ 1.25133936,  0.13713895,  0.60196908,  0.34365569],
       [ 0.16496757, -0.80324245,  0.71644814,  0.47583095],
       [ 1.61346329, -0.0979564 ,  1.11712487,  0.47583095],
       [ 0.5270915 ,  0.60732966,  0.48749002,  0.47583095],
       [-1.0421122 ,  0.60732966, -1.40141454, -1.37462275],
       [ 0.28567554, -1.0383378 ,  1.0026458 ,  0.21148042],
       [-0.43857231, -1.5085285 , -0.08490531, -0.31722063],
       [-0.31786434, -0.0979564 ,  0.14405282,  0.07930516],
       [-1.76636006, -0.33305175, -1.40141454, -1.37462275],
       [ 0.64779947,  0.37223431,  0.83092721,  1.4010578 ],
       [ 1.0099234 ,  0.60732966,  1.05988534,  1.13670727],
       [ 0.88921543, -0.0979564 ,  0.31577142,  0.21148042],
       [ 2.21700317, -1.0383378 ,  1.74675972,  1.4010578 ],
       [-1.28352815, -0.0979564 , -1.40141454, -1.50679801],
       [-0.55928029,  1.54771106, -1.34417501, -1.37462275],
       [ 0.64779947, -0.5681471 ,  1.0026458 ,  1.13670727],
       [ 0.88921543, -0.33305175,  0.43025048,  0.07930516]])

In [11]:
X_train_scaled

array([[-0.31786434, -0.33305175, -0.14214484,  0.07930516],
       [-0.31786434, -0.0979564 ,  0.37301095,  0.34365569],
       [-1.0421122 ,  1.31261571, -1.40141454, -1.37462275],
       [-0.92140422,  1.07752036, -1.40141454, -1.37462275],
       [-0.55928029,  0.84242501, -1.22969595, -1.37462275],
       [ 1.0099234 , -0.0979564 ,  0.77368768,  1.4010578 ],
       [-0.31786434, -0.5681471 ,  0.60196908,  1.00453201],
       [ 0.5270915 , -1.74362386,  0.31577142,  0.07930516],
       [-0.43857231, -1.74362386,  0.08681329,  0.07930516],
       [-0.80069624, -0.80324245,  0.02957376,  0.21148042],
       [ 0.16496757,  0.84242501,  0.37301095,  0.47583095],
       [-1.16282017, -0.0979564 , -1.40141454, -1.37462275],
       [-0.31786434, -1.27343315,  0.02957376, -0.18504537],
       [-0.92140422, -1.27343315, -0.48558203, -0.18504537],
       [-0.07644839, -0.80324245,  0.14405282, -0.31722063],
       [ 0.04425959, -0.0979564 ,  0.20129235,  0.34365569],
       [-0.80069624,  2.48809247, -1.34417501, -1.50679801],
       [ 1.0099234 , -0.0979564 ,  0.65920861,  0.60800622],
       [ 1.73417126, -0.33305175,  1.40332253,  0.74018148],
       [-0.43857231,  1.07752036, -1.45865408, -1.37462275],
       [ 2.21700317, -0.5681471 ,  1.63228066,  1.00453201],
       [-0.19715636, -0.0979564 ,  0.20129235, -0.05287011],
       [ 2.21700317, -0.0979564 ,  1.28884346,  1.4010578 ],
       [-0.55928029, -0.0979564 ,  0.37301095,  0.34365569],
       [ 1.0099234 ,  0.13713895,  1.0026458 ,  1.53323307],
       [ 1.0099234 ,  0.60732966,  1.05988534,  1.66540833],
       [ 1.85487924, -0.5681471 ,  1.28884346,  0.87235674],
       [-1.16282017,  0.13713895, -1.34417501, -1.50679801],
       [-0.07644839, -0.5681471 ,  0.71644814,  1.53323307],
       [-0.43857231, -1.0383378 ,  0.31577142, -0.05287011],
       [-0.19715636, -1.27343315,  0.65920861,  1.00453201],
       [-1.28352815, -0.0979564 , -1.40141454, -1.24244748],
       [ 0.28567554, -0.5681471 ,  0.08681329,  0.07930516],
       [ 1.0099234 , -1.27343315,  1.11712487,  0.74018148],
       [ 0.64779947, -0.80324245,  0.83092721,  0.87235674],
       [-0.92140422,  0.60732966, -1.22969595, -0.97809696],
       [ 2.09629519, -0.0979564 ,  1.57504113,  1.13670727],
       [-0.55928029,  0.84242501, -1.34417501, -1.11027222],
       [-0.07644839, -0.80324245,  0.71644814,  0.87235674],
       [ 1.25133936,  0.13713895,  0.88816674,  1.13670727],
       [ 0.16496757, -1.97871921,  0.65920861,  0.34365569],
       [ 0.64779947,  0.13713895,  0.94540627,  0.74018148],
       [-1.16282017, -1.27343315,  0.37301095,  0.60800622],
       [-0.19715636, -1.0383378 , -0.19938437, -0.31722063],
       [-1.88706803, -0.0979564 , -1.57313314, -1.50679801],
       [ 0.5270915 , -0.33305175,  1.0026458 ,  0.74018148],
       [-1.5249441 ,  0.84242501, -1.40141454, -1.24244748],
       [ 0.76850745, -0.0979564 ,  0.77368768,  1.00453201],
       [-0.80069624,  0.84242501, -1.40141454, -1.37462275],
       [-0.92140422,  1.78280641, -1.34417501, -1.24244748],
       [ 0.76850745, -0.0979564 ,  0.94540627,  0.74018148],
       [-1.28352815,  0.84242501, -1.11521688, -1.37462275],
       [ 1.25133936,  0.37223431,  1.05988534,  1.4010578 ],
       [ 2.21700317,  1.78280641,  1.63228066,  1.26888254],
       [-0.92140422,  1.07752036, -1.40141454, -1.24244748],
       [-1.16282017,  1.31261571, -1.40141454, -1.50679801],
       [-0.67998827,  1.54771106, -1.34417501, -1.37462275],
       [ 0.5270915 , -0.5681471 ,  0.71644814,  0.34365569],
       [-0.07644839, -0.80324245,  0.71644814,  0.87235674],
       [ 0.40638352, -1.97871921,  0.37301095,  0.34365569],
       [-1.0421122 , -2.44890991, -0.19938437, -0.31722063],
       [ 0.04425959, -0.0979564 ,  0.71644814,  0.74018148],
       [-0.07644839, -0.80324245,  0.02957376, -0.05287011],
       [-0.19715636, -0.5681471 ,  0.37301095,  0.07930516],
       [-1.0421122 , -1.74362386, -0.31386343, -0.31722063],
       [-0.80069624,  1.07752036, -1.34417501, -1.37462275],
       [-1.0421122 ,  1.07752036, -1.45865408, -1.24244748],
       [ 0.5270915 , -1.27343315,  0.65920861,  0.87235674],
       [ 2.45841912,  1.78280641,  1.46056206,  1.00453201],
       [-0.19715636, -0.33305175,  0.20129235,  0.07930516],
       [-1.76636006,  0.37223431, -1.45865408, -1.37462275],
       [-1.76636006, -0.0979564 , -1.45865408, -1.37462275],
       [-0.19715636,  3.19337852, -1.34417501, -1.11027222],
       [-1.0421122 ,  1.07752036, -1.28693548, -0.84592169],
       [ 0.64779947, -0.5681471 ,  1.0026458 ,  1.26888254],
       [ 0.5270915 ,  0.60732966,  1.23160393,  1.66540833],
       [ 1.25133936,  0.13713895,  0.71644814,  1.4010578 ],
       [-0.92140422,  1.78280641, -1.11521688, -1.11027222],
       [-0.31786434, -0.80324245,  0.20129235,  0.07930516],
       [ 0.40638352, -0.33305175,  0.25853189,  0.07930516],
       [ 1.61346329,  1.31261571,  1.28884346,  1.66540833],
       [ 0.5270915 , -0.80324245,  0.60196908,  0.74018148],
       [-0.19715636, -0.5681471 ,  0.14405282,  0.07930516],
       [-0.43857231,  2.72318782, -1.40141454, -1.37462275],
       [ 1.13063138, -0.5681471 ,  0.54472955,  0.21148042],
       [-1.28352815,  0.84242501, -1.28693548, -1.37462275],
       [ 0.76850745,  0.37223431,  0.71644814,  1.00453201],
       [ 0.28567554, -0.0979564 ,  0.60196908,  0.74018148],
       [-1.40423613,  0.37223431, -1.28693548, -1.37462275],
       [ 0.28567554, -0.0979564 ,  0.43025048,  0.21148042],
       [-0.92140422,  0.84242501, -1.34417501, -1.37462275],
       [-0.43857231, -1.27343315,  0.08681329,  0.07930516],
       [ 0.40638352,  0.84242501,  0.88816674,  1.4010578 ],
       [ 0.76850745, -0.0979564 ,  1.11712487,  1.26888254],
       [ 0.76850745, -0.5681471 ,  0.43025048,  0.34365569],
       [-1.0421122 ,  0.37223431, -1.51589361, -1.37462275],
       [-1.16282017,  0.13713895, -1.34417501, -1.37462275],
       [-1.5249441 ,  1.31261571, -1.63037267, -1.37462275],
       [-0.92140422,  1.54771106, -1.34417501, -1.11027222],
       [ 0.64779947, -0.33305175,  0.25853189,  0.07930516],
       [-0.07644839, -1.0383378 ,  0.08681329, -0.05287011],
       [ 1.0099234 ,  0.13713895,  0.31577142,  0.21148042],
       [ 0.16496757, -0.33305175,  0.37301095,  0.34365569],
       [ 1.25133936,  0.13713895,  0.60196908,  0.34365569],
       [ 0.16496757, -0.80324245,  0.71644814,  0.47583095],
       [ 1.61346329, -0.0979564 ,  1.11712487,  0.47583095],
       [ 0.5270915 ,  0.60732966,  0.48749002,  0.47583095],
       [-1.0421122 ,  0.60732966, -1.40141454, -1.37462275],
       [ 0.28567554, -1.0383378 ,  1.0026458 ,  0.21148042],
       [-0.43857231, -1.5085285 , -0.08490531, -0.31722063],
       [-0.31786434, -0.0979564 ,  0.14405282,  0.07930516],
       [-1.76636006, -0.33305175, -1.40141454, -1.37462275],
       [ 0.64779947,  0.37223431,  0.83092721,  1.4010578 ],
       [ 1.0099234 ,  0.60732966,  1.05988534,  1.13670727],
       [ 0.88921543, -0.0979564 ,  0.31577142,  0.21148042],
       [ 2.21700317, -1.0383378 ,  1.74675972,  1.4010578 ],
       [-1.28352815, -0.0979564 , -1.40141454, -1.50679801],
       [-0.55928029,  1.54771106, -1.34417501, -1.37462275],
       [ 0.64779947, -0.5681471 ,  1.0026458 ,  1.13670727],
       [ 0.88921543, -0.33305175,  0.43025048,  0.07930516]])

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
X_train_scaled

array([[0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.91666667, 0.41666667, 0.94915254, 0.83333333],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.19444444, 0.125     , 0.38983051, 0.375     ],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.58333333, 0.5       , 0.72881356, 0.91666667],
       [0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.58333333, 0.33333333, 0.77966102, 0.83333333],
       [0.63888889, 0.375     , 0.61016949, 0.5       ]])

In [14]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [19]:
data = fetch_openml('adult', version=1, as_frame=True, parser='auto').frame

In [20]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,United-States,>50K

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [24]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded_values = encoder.fit_transform(data[['occupation', 'race']])

new_cols = encoder.get_feature_names_out(['occupation', 'race'])

In [25]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [28]:
df_encoded = pd.DataFrame(encoded_values, columns=new_cols, index = data.index)

In [30]:
data_final = pd.concat(
    [data.drop(columns=['occupation', 'race']), df_encoded],
    axis = 1
)

In [31]:
data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,...,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516,Bachelors,13,Never-married,Not-in-family,Male,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,Private,215646,HS-grad,9,Divorced,Not-in-family,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,Private,234721,11th,7,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Not-in-family,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,4,NaN,321403,HS-grad,9,Widowed,Other-relative,Male,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,2,Private,83891,Bachelors,13,Divorced,Own-child,Male,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0